Formatting

diff --git a/cloud/aws/iam/escalate-old-iam-user/escalate-old-iam-user.yaml b/cloud/aws/iam/escalate-old-iam-user/escalate-old-iam-user.yaml
--- a/cloud/aws/iam/escalate-old-iam-user/escalate-old-iam-user.yaml
+++ b/cloud/aws/iam/escalate-old-iam-user/escalate-old-iam-user.yaml
@@ -10,10 +10,12 @@ steps:
   - name: ensure-aws-creds-present
     inline: |
       set -e
+
       if [[ -z "${AWS_DEFAULT_REGION}" ]]; then
         echo "error: AWS_DEFAULT_REGION must be set."
         exit 1
       fi
+
       if [[ -n "${AWS_ACCESS_KEY_ID}" && -n "${AWS_SECRET_ACCESS_KEY}" ]]; then
         if [[ -z "${AWS_SESSION_TOKEN}" ]]; then
           echo "warning: AWS_SESSION_TOKEN is not set with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY."
@@ -21,6 +23,11 @@ steps:
       elif [[ -z "${AWS_PROFILE}" ]]; then
         echo "error: AWS credentials are not set, exiting."
         exit 1
+      fi
+
+      if ! command -v aws &> /dev/null; then
+          echo "Error: aws cli is not installed on the current system, can't run enumerate-iam"
+          exit 1
       fi
 
   - name: ensure-aws-cli-present
@@ -37,7 +44,8 @@ steps:
     inline: |
       set -e
       # Add the user to the group
-      aws iam add-user-to-group --user-name {{args.user}} --group-name {{args.group}}
+      aws iam add-user-to-group --user-name {{args.user}} \
+        --group-name {{args.group}}
 
     cleanup:
       name: cleanup
@@ -45,5 +53,6 @@ steps:
         set -e
         if [[ "{{args.cleanup}}" == true ]]; then
           # Remove the user from the group
-          aws iam remove-user-from-group --user-name {{args.user}} --group-name {{args.group}}
+          aws iam remove-user-from-group --user-name {{args.user}} \
+            --group-name {{args.group}}
         fi
