Enhancements to IAM Enumeration and S3 Bucket Enumeration TTPs (#107)
Summary:
Pull Request resolved: https://github.com/facebookincubator/ForgeArmory/pull/107

**Added:**

- New `bucket-enum` TTP for enumerating open S3 buckets using the S3Scanner tool.
- New `aws-connector` helper TTP for validating AWS credentials and region settings.

**Changed:**

- Updated `enumerate-iam` README and YAML to clarify requirements and examples.
- Removed unnecessary `set -e` commands in `enumerate-iam.yaml`.
- Updated `bucket-enum` README to reflect the addition of new arguments and the use of the S3Scanner tool.
- Updated `bucket-enum.yaml` to include the `aws-connector` step, revised the `provision` step for better tool installation, and added cleanup actions.
- Modified `suid-binary-escalation.yaml` to improve the `hunt-for-suid-bins` and `escalate-privilege` steps for better clarity and effectiveness.

Reviewed By: cedowens

Differential Revision: D54397852

fbshipit-source-id: 7f9c556b30e2bca5b2639012cf361d3e55e42714

diff --git a/ttps/privilege-escalation/suid-binary-escalation/suid-binary-escalation.yaml b/ttps/privilege-escalation/suid-binary-escalation/suid-binary-escalation.yaml
--- a/ttps/privilege-escalation/suid-binary-escalation/suid-binary-escalation.yaml
+++ b/ttps/privilege-escalation/suid-binary-escalation/suid-binary-escalation.yaml
@@ -42,18 +42,17 @@ steps:
   - name: hunt-for-suid-bins
     inline: |
       su - {{ .Args.low_priv_user }}
-      find /usr/bin /usr/local/bin -perm -4000 2>/dev/null
+      find /usr/bin /usr/local/bin -type f -perm -4000 -executable -print 2>/dev/null
 
   - name: escalate-privilege
     description: "Use {{ .Args.vuln_bin }} SUID binary to escalate privileges of {{ .Args.low_priv_user }}"
     inline: |
       su - {{ .Args.low_priv_user }}
-      output="$({{ .Args.vuln_bin }} {{ .Args.escalation_params }})"
-      echo "Checking results"
-      if [ "$output" == "root" ]; then
-        echo "TTP Ran Successfully"
-        exit 0
-      else
-      echo "TTP failed"
+      {{ .Args.vuln_bin }} {{ .Args.escalation_params }}
+      if [ "$?" -ne 0 ]; then
+        echo "Failed to escalate privileges" >&2
         exit 1
       fi
+
+      echo "Privileges escalated successfully" >&2
+      exit 0
