Create role, Access Role (#120)
Summary:
Pull Request resolved: https://github.com/facebookincubator/ForgeArmory/pull/120

Create Role TTP and Access Role TTP to be opensourced

Differential Revision: D59923648

diff --git a/ttps/helpers/cloud/aws/validate-aws-env-configured.yaml b/ttps/helpers/cloud/aws/validate-aws-env-configured.yaml
--- a/ttps/helpers/cloud/aws/validate-aws-env-configured.yaml
+++ b/ttps/helpers/cloud/aws/validate-aws-env-configured.yaml
@@ -35,3 +35,15 @@ steps:
       else
         echo -e "AWS CLI is installed: $(aws --version)"
       fi
+
+  - name: check_jq_install
+    description: "Ensure JQ is installed. JQ is required to run some of the cloud TTPs"
+    inline: |
+      set -e
+
+      if ! [[ -x "$(command -v jq)" ]]; then
+        echo 'Error: jq is not installed.. Quitting !!' >&2
+        exit 1
+      else
+        echo -e "jq is installed: $(jq --version)"
+      fi
