Uniformity and modularity

diff --git a/cloud/aws/iam/enumerate-iam/enumerate-iam.yaml b/cloud/aws/iam/enumerate-iam/enumerate-iam.yaml
--- a/cloud/aws/iam/enumerate-iam/enumerate-iam.yaml
+++ b/cloud/aws/iam/enumerate-iam/enumerate-iam.yaml
@@ -11,7 +11,7 @@ args:
   - name: extended_scan
 
 steps:
-  - name: setup
+  - name: ensure-aws-creds-present
     inline: |
       set -e
 
@@ -29,6 +29,20 @@ steps:
           exit 1
       fi
 
+  - name: ensure-aws-cli-present
+    inline: |
+      set -e
+
+      if ! [ -x "$(command -v aws)" ]; then
+        echo 'Error: AWS CLI is not installed.' >&2
+      else
+        echo -e "AWS CLI is installed: $(aws --version)"
+      fi
+
+  - name: ensure-dependencies-present
+    inline: |
+      set -e
+
       if ! command -v python3 &> /dev/null; then
           echo "Error: Python3 is not installed on the current system, cannot run enumerate-iam"
           exit 1
@@ -44,10 +58,9 @@ steps:
           exit 1
       fi
 
-      if ! command -v aws &> /dev/null; then
-          echo "Error: aws cli is not installed on the current system, can't run enumerate-iam"
-          exit 1
-      fi
+  - name: setup
+    inline: |
+      set -e
 
       if [[ -d "{{args.eiam_path}}" ]]; then
           echo "Info: enumerate-iam already present on the current system"
diff --git a/cloud/aws/iam/revive-old-iam-user/revive-old-iam-user.yaml b/cloud/aws/iam/revive-old-iam-user/revive-old-iam-user.yaml
--- a/cloud/aws/iam/revive-old-iam-user/revive-old-iam-user.yaml
+++ b/cloud/aws/iam/revive-old-iam-user/revive-old-iam-user.yaml
@@ -5,31 +5,34 @@ args:
   - name: cleanup
   - name: detect
   - name: user
+
 steps:
   - name: ensure-aws-creds-present
     inline: |
       set -e
+
       if [[ -z "${AWS_DEFAULT_REGION}" ]]; then
-        echo "error: AWS_DEFAULT_REGION must be set."
-        exit 1
+          echo "Error: AWS_DEFAULT_REGION must be set."
+          exit 1
       fi
+
       if [[ -n "${AWS_ACCESS_KEY_ID}" && -n "${AWS_SECRET_ACCESS_KEY}" ]]; then
-        if [[ -z "${AWS_SESSION_TOKEN}" ]]; then
-          echo "warning: AWS_SESSION_TOKEN is not set with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY."
-        fi
+          if [[ -z "${AWS_SESSION_TOKEN}" ]]; then
+            echo "Warning: AWS_SESSION_TOKEN is not set with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY."
+          fi
       elif [[ -z "${AWS_PROFILE}" ]]; then
-        echo "error: AWS credentials are not set, exiting."
-        exit 1
+          echo "Error: AWS credentials are not set, exiting."
+          exit 1
       fi
 
   - name: ensure-aws-cli-present
     inline: |
       set -e
+
       if ! [ -x "$(command -v aws)" ]; then
-        echo 'error: AWS CLI is not installed.' >&2
+        echo 'Error: AWS CLI is not installed.' >&2
       else
-        echo 'AWS CLI is installed.'
-        aws --version
+        echo -e "AWS CLI is installed: $(aws --version)"
       fi
 
   - name: add-access-key
diff --git a/cloud/aws/secretsmanager/steal-secretsmanager-secret/steal-secretsmanager-secret.yaml b/cloud/aws/secretsmanager/steal-secretsmanager-secret/steal-secretsmanager-secret.yaml
--- a/cloud/aws/secretsmanager/steal-secretsmanager-secret/steal-secretsmanager-secret.yaml
+++ b/cloud/aws/secretsmanager/steal-secretsmanager-secret/steal-secretsmanager-secret.yaml
@@ -10,7 +10,7 @@ args:
   - name: target_secret_id
 
 steps:
-  - name: setup
+  - name: ensure-aws-creds-present
     inline: |
       set -e
       if [[ -z "${AWS_DEFAULT_REGION}" ]]; then
@@ -26,9 +26,14 @@ steps:
           exit 1
       fi
 
-      if ! command -v aws &> /dev/null; then
-          echo "Error: aws cli is not installed on the current system, can't run enumerate-iam"
-          exit 1
+  - name: ensure-aws-cli-present
+    inline: |
+      set -e
+
+      if ! [ -x "$(command -v aws)" ]; then
+        echo 'Error: AWS CLI is not installed.' >&2
+      else
+        echo -e "AWS CLI is installed: $(aws --version)"
       fi
 
   - name: steal-secret
